cask_args appdir: "/Applications"

cask "visual-studio-code"
cask "intellij-idea"
cask "vlc"
cask "postico"
cask "telegram"
cask "google-chrome"
cask "tabby"
cask "postman"

# System
brew "curl"
brew "wget"
brew "git"
brew "openssl"
brew "coreutils"
brew "moreutils"
brew "findutils"
brew "binutils"
brew "gnu-sed"
brew "gnu-tar"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"
brew "tree"
brew "htop"
brew "pidof"
brew "pstree"
brew "grep"
brew "openssh"
brew "rsync"
brew "ssh-copy-id"
brew "dnstracer"
brew "sslscan"
brew "watch"
brew "telnet"
brew "gnupg"
brew "jq"
brew "knqyf263/pet/pet"

# Dev
brew "go"
brew "cmake"
brew "scala"
brew "sbt"